services:
  backend:
    image: th/backflask
    build: .
    ports:
      - 5000:5000
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16.2-alpine3.19
    restart: always
    volumes:
      - ./db_create.sql:/docker-entrypoint-initdb.d/db_create.sql
    user: postgres
    environment:
      - POSTGRES_PASSWORD=TH
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2.4-alpine3.19
    ports:
      - 6379:6379
