groupMeet_details="שלום {0} היקר,יש לבצע פגישה קבוצתית אחת ל60 יום"
personalMeet_details="שלום {0} היקר,יש לבצע פגישה עם {1}"
personalCall_details="שלום {0} היקר,יש לבצע שיחה עם {1}"
basisVisit_details="שלום {0} היקר,יש לבצע 3 סבבי בסיסים בשנה"
event_details="שלום {0} היקר,בתאריך {1} יחול אירוע {2} ל{3}"