### Common Columns ###
ID_COL = "id"
NAME_COL = "name"
CLUSTER_ID_COL = "cluster_id"
ADDRESS_COL = "address"
CITY_ID_COL = "city_id"
PHONE_COL = "phone"
EMAIL_COL = "email"
BIRTHDAY_COL = "birthday"
INSTITUTION_ID_COL = "institution_id"

### Contact Forms Table ###
CONTACT_FORMS_TBL = "contact_forms"
SUBJECT_COL = "subject"
CONTENT_COL = "content"
CREATED_AT_COL = "created_at"
CREATED_BY_ID_COL = "created_by_id"
WAS_READ_COL = "allreadyread"

### Clusters Table ###
CLUSTERS_TBL = "clusters"

### Cities Table ###
CITIES_TBL = "cities"

### Roles Table ###
ROLES_TBL = "roles"

### Institutions Table ###
INSTITUTIONS_TBL = "institutions"
CONTACT_NAME_COL = "contact_name"
CONTACT_PHONE_COL = "contact_phone"
LOGO_PATH_COL = "logo_path"
OWNER_ID_COL = "owner_id"

### Users Table ###
USERS_TBL = "user1"
LAST_NAME_COL = "last_name"
ROLE_ID_COL = "role_id"
PHOTO_PATH_COL = "photo_path"
NOTIFY_START_WEEK_COL = "notifystartweek"
NOTIFY_DAY_BEFORE_COL = "notifydaybefore"
NOTIFY_MORNING_COL = "notifymorning"

### Students Table ###
APPRENTICES_TBL = "apprentice"
ACCOMPANY_ID_COL = "accompany_id"
MARRIAGE_STATUS_COL = "marriage_status"
MARRIAGE_DATE_COL = "marriage_date"
WIFE_NAME_COL = "wife_name"
WIFE_PHONE_COL = "wife_phone"
FATHER_NAME_COL = "father_name"
FATHER_PHONE_COL = "father_phone"
FATHER_EMAIL_COL = "father_email"
MOTHER_NAME_COL = "mother_name"
MOTHER_PHONE_COL = "mother_phone"
MOTHER_EMAIL_COL = "mother_email"
HIGH_SCHOOL_NAME_COL = "high_school_name"
HIGH_SCHOOL_TEACHER_COL = "high_school_teacher"
HIGH_SCHOOL_TEACHER_PHONE_COL = "high_school_teacher_phone"
PRE_ARMY_INSTITUTION_COL = "pre_army_institution"
TEACHER_GRADE_A_COL = "teacher_grade_a"
TEACHER_GRADE_A_PHONE_COL = "teacher_grade_a_phone"
TEACHER_GRADE_B_COL = "teacher_grade_b"
TEACHER_GRADE_B_PHONE_COL = "teacher_grade_b_phone"
HADAR_PLAN_SESSION_COL = "hadar_plan_session"
BASE_ADDRESS_COL = "base_address"
UNIT_NAME_COL = "unit_name"
ARMY_ROLE_COL = "army_role"
SERVE_TYPE_COL = "serve_type"
RECRUITMENT_DATE_COL = "recruitment_date"
RELEASE_DATE_COL = "release_date"
PAYING_COL = "paying"
SPIRIT_STATUS_COL = "spirit_status"
ACCOMPANY_CONNECT_STATUS_COL = "accompany_connect_status"
WORK_STATUS_COL = "workstatus"
WORK_PLACE_COL = "workplace"
WORK_TYPE_COL = "worktype"
WORK_OCCUPATION_COL = "workoccupation"
EDUCATION_FACULTY_COL = "educationfaculty"
EDUCATIONAL_INSTITUTION_COL = "educationalinstitution"
MILITARY_POSITION_OLD_COL = "militarypositionold"
MILITARY_UPDATED_DATETIME_COL = "militaryupdateddatetime"
HIGH_SCHOOL_TEACHER_EMAIL_COL = "high_school_teacher_email"
TEACHER_GRADE_A_EMAIL_COL = "teacher_grade_a_email"
TEACHER_GRADE_B_EMAIL_COL = "teacher_grade_b_email"

### Visits Table ###
VISITS_TBL = "visits"
APPRENTICE_ID_COL = "apprentice_id"
VISIT_DATE_COL = "visit_date"
USER_ID_COL = "user_id"
VISIT_IN_ARMY_COL = "visit_in_army"
NOTE_COL = "note"
TITLE_COL = "title"

ALREADY_READ = "allreadyread"
